### ISSUE TITLE
Double or CGFloat?

### ISSUE THREAD

**Issue by katopz** [rhodgkins/UIView-IBInspectable#1]
Your extension is working great, Just one thing I curious here...

``` swift
    @IBInspectable var cornerRadius: Double {
        get {
            return Double(self.layer.cornerRadius)
        }
        set {
            self.layer.cornerRadius = CGFloat(newValue)
        }
    }
```

Can we use CGFloat instead of Double like this?

``` swift
    @IBInspectable var cornerRadius: CGFloat {
        get {
            return self.layer.cornerRadius
        }
        set {
            self.layer.cornerRadius = newValue
        }
    }
```

Should be some reason there?

Thanks

**Comment by rhodgkins** [comment]
I've kept to using Swift types as half of UIKit is already bad enough filled with `CGFloat`s!

If you want to assign a `CGFloat` to a `Double` you can just do:

``` swift
let value: CGFloat = 1.0
view.cornerRadius = Double(value)
```

**Comment by katopz** [comment]
Cool, My next question would be why Double instead of Float? (Sorry for noobs question, I got plenty)

**Comment by rhodgkins** [comment]
`CGFloat` is a `Double` on 64-bit platforms, so using this means precision will never be lost.

For questions like this please use [StackOverflow](http://stackoverflow.com/)! :)
